language: node_js
sudo: false
install:
- npm install mocha -g
- npm install
before_script:
- wget http://dl.nwjs.io/v0.11.6/chromedriver-nw-v0.11.6-linux-x64.tar.gz
- wget http://dl.nwjs.io/v0.11.6/node-webkit-v0.11.6-linux-x64.tar.gz
- wget http://selenium-release.storage.googleapis.com/2.43/selenium-server-standalone-2.43.0.jar
- tar -zxvf chromedriver-nw-v0.11.6-linux-x64.tar.gz
- mv chromedriver-nw-v0.11.6-linux-x64/chromedriver ./
- tar -zxvf node-webkit-v0.11.6-linux-x64.tar.gz
- mv node-webkit-v0.11.6-linux-x64/* ./
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 5
- java -jar selenium-server-standalone-2.43.0.jar -Dwebdriver.chrome.driver=./chromedriver &
- sleep 10
script:
- npm test
before_deploy:
- npm install -g grunt-cli
- grunt build
- sh tests/before_deploy.sh
deploy:
  provider: releases
  api_key:
    secure: TYrr9UQG6b23nENn++ExDRLXuqTeskcwWBQrdlxoWaeU0C/ItjLsgTGWUU+L/CCCdpL3td6wKTjNvBTfrM4VFvpCSV5ONCXG54+5mKTZwV5TGoO9aT4KmW8IgnXWlJsJEQOKW5zRSsYNWP+n/QD0J3NGxtqmnvBoIRj+pxGTCjc=
  file:
  - "MarknoteMac.zip"
  - "MarknoteWin.zip"
  - "MarknoteLinux.zip"
  skip_cleanup: true
  on:
    tags: true
    repo: octalmage/Marknote
    all_branches: true
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cebb2a5d2ce11e1dd8e2
    on_success: always
    on_failure: always 
    on_start: false   